CREATE TABLE `production_defect_history` (
  `production_defect_history_id` int(11) NOT NULL AUTO_INCREMENT,
  `project` varchar(1000) NOT NULL,
  `area` varchar(1000) NOT NULL,
  `bugid` int(11) NOT NULL,  
  `Title` varchar(128) NOT NULL,
  `Status` varchar(50) NOT NULL,
  `Priority` varchar(50) NOT NULL,
  `Category` varchar(50) NOT NULL,
  `ProdDefect` varchar(255) NOT NULL,
  `InjectedLast90` varchar(255) NOT NULL,
  `ClientReporting` varchar(4000) NULL,
  `dtOpened` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `dtClosed` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `daysOpen` int(11) NOT NULL,
  `day` int(11) NOT NULL,
  `month` int(11) NOT NULL,
  `year` int(11) NOT NULL,
  `hotfix` bit NOT NULL,  
  `person_assigned_to_id` int(11) NOT NULL,  
  `person_assigned_to_name` varchar(50) NOT NULL,  
  `person_opened_by_id` int(11) NOT NULL,  
  `person_opened_by_name` varchar(50) NOT NULL,  
  `inserted_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `inserted_by` varchar(100) NOT NULL,
  PRIMARY KEY (`production_defect_history_id`),
   INDEX (project,area, day, month, year),
   INDEX (project,area),
   INDEX (bugid)
) ENGINE=InnoDB AUTO_INCREMENT=6216 DEFAULT CHARSET=latin1;
