CREATE TABLE `production_story_history` (
  `production_story_history_id` int(11) NOT NULL AUTO_INCREMENT,
  `project` varchar(1000) NOT NULL,
  `area` varchar(1000) NOT NULL,
  `bugid` int(11) NOT NULL,
  `Title` varchar(128) NOT NULL,
  `Status` varchar(50) NOT NULL,
  `Priority` varchar(50) NOT NULL,
  `Category` varchar(50) NOT NULL,
  `ClientReporting` varchar(4000) DEFAULT NULL,
  `dtOpened` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `dtClosed` timestamp NULL DEFAULT '0000-00-00 00:00:00',
  `daysOpen` int(11) NOT NULL,
  `day` int(11) NOT NULL,
  `month` int(11) NOT NULL,
  `year` int(11) NOT NULL,
  `external_commitment_id` int(11) DEFAULT NULL,
  `commitment_name` varchar(255) NOT NULL,
  `committed_dt` timestamp NULL DEFAULT NULL,
  `min_dt_rolled_to_prod` timestamp NULL DEFAULT NULL,
  `person_assigned_to_id` int(11) DEFAULT NULL,
  `person_assigned_to_name` varchar(50) DEFAULT NULL,
  `person_opened_by_id` int(11) DEFAULT NULL,
  `person_opened_by_name` varchar(50) DEFAULT NULL,
  `inserted_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `inserted_by` varchar(100) NOT NULL,
  PRIMARY KEY (`production_story_history_id`),
  KEY `project_s` (`project`(767),`area`(767),`day`,`month`,`year`),
  KEY `project_s_2` (`project`(767),`area`(767)),
  KEY `bugid_s` (`bugid`),
  KEY `IX_prod_story_history_project` (`project`(767)),
  KEY `IX_Prod_story_history_bugquery` (`project`(767),`Category`,`Title`,`Priority`)
) ENGINE=InnoDB AUTO_INCREMENT=53009580 DEFAULT CHARSET=latin1;

